#!/usr/bin/env bash
cd ..
source .env
git config --global user.email $GIT_EMAIL
git config --global user.name $GIT_NAME
git config --global core.autocrlf input
git init
git branch -M main
git remote add origin $REMOTE_REPO
git remote set-url origin $REMOTE_REPO
